### PR TITLE
Update DASH to cm-13.0 version.

### PR DESCRIPTION
**Pull request by Haxk20**
needs testing.
If it doesnt work we will revert this.

### CODE REVIEW

**Comment by DaniPhii** [comment]
Let's test it then. ^^

**Comment by Haxk20** [comment]
Downloading sources cannot test it.
If you can please do so

**Comment by DaniPhii** [comment]
Do you mean that I test it? 🤔

**Comment by Haxk20** [comment]
yeah if you can please I'm working on multirom now so cannot build

**Comment by DaniPhii** [comment]
I tested it and it compiled. But screen was constantly on, no brightness control.

**Comment by Haxk20** [comment]
Will look into it.
Maybe you can too i have lot of work with CM-13.0 errors kinda.

**Pull request merged**
